### ISSUE TITLE
HTTPError: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by Michl7** [Delivator/pr0-bot#1]
I set up your bot and always get an HTTPError: Response code 403 (Forbidden) when posting a programm link.

**Comment by Delivator** [comment]
Yeah they made the API which was previously open to all closed, so that you have to be authorized to get any post info. I'll have to figure something out to allow users to sign in with their pr0gramm account.
If you know how to fix that feel free so send a pull request!

**Comment by Michl7** [comment]
Hi Delivator,

thx for your answer. One of the Pr0 Devs made a bot already:
https://github.com/pr0-dev/Discord-Bot

BR
Michl

**Comment by Delivator** [comment]
Great, didn't know about that!
I think I'll archive this repo then.
